### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by Steb03**

### CODE REVIEW

**Comment by vercte** [comment]
lol I can see why you made this

I named it `scr` after script, though; also it isn’t really a necessary change

Thank you for checking out my website!

**Comment by Steb03** [comment]
> lol I can see why you made this
> 
> I named it `scr` after script, though; also it isn’t really a necessary change

Oh, shoot! 😅 I guess that's pretty cool.

> Thank you for checking out my website!

No problemo. It's so cool how you make all sorts of animations, and to think it is made with vanilla code! I would think that you use Vue or something!

Are you still working on drawing station? (this is ILTMS btw)

**Comment by veloce-vasta** [comment]
> lol I can see why you made this
> 
> I named it `scr` after script, though; also it isn’t really a necessary change

Oh, shoot! 😅 I guess that's pretty cool.

> Thank you for checking out my website!

No problemo. It's so cool how you make all sorts of animations, and to think it is made with vanilla code! I would think that you use Vue or something!

Are you still working on drawing station? (this is ILTMS btw)

**Comment by vercte** [comment]
ohh, I was wondering who you were!

I’m not working on it really, but I’m considering a third, more professional iteration for it that can be used as an actual reliable drawing tool.

**Comment by Steb03** [comment]
> lol I can see why you made this
> 
> I named it `scr` after script, though; also it isn’t really a necessary change

Oh, shoot! 😅 I guess that's pretty cool.

> Thank you for checking out my website!

No problemo. It's so cool how you make all sorts of animations, and to think it is made with vanilla code! I would think that you use Vue or something!

Are you still working on drawing station? (this is ILTMS btw)


> ohh, I was wondering who you were!
> 
> I’m not working on it really, but I’m considering a third, more professional iteration for it that can be used as an actual reliable drawing tool.

Cool! You should add an svg editor thing as well, and then let the user copy and paste the html svg tag that is generated.

**Comment by vercte** [comment]
Ooh, yes! I am definitely considering making an svg editor now, it seems
like a cool project. Although, maybe something separate from the new
Drawing Station, as one is art and the other is more design. They’ll be
both on GitHub eventually, if you’d like to contribute!

**Comment by vercte** [comment]
On Thu, Dec 1, 2022 at 7:22 PM Vercte ***@***.***> wrote:

> Ooh, yes! I am definitely considering making an svg editor now, it seems
> like a cool project. Although, maybe something separate from the new
> Drawing Station, as one is art and the other is more design. They’ll be
> both on GitHub eventually, if you’d like to contribute!

Oh, and you can also always fork the current Drawing Station if you want to
edit my (compared to now, horrible) code and add some new features. The
next Drawing Station will probably use ES6 module syntax and be split up
into multiple files for *way* better editing.

**Pull request closed without merging**
